### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by LReiz** [LReiz/PandemicChess#1]
- [x] **Interface Inicial**
     - [x] Selecionar Modo
     - [x] Escolher time Multiplayer Remoto
- [x] **Multiplayer Remoto**
- [x] **Interface Final (Vitória ou Derrota!)**
     - [x] Mensagem final para cada time
     - [ ] Tecla para reiniciar jogo
- [x] **Tabuleiro**
     - [x] Alternância da vez do jogador
     - [x] Gráficos do mapa
     - [x] Criar condições de Vitória (determinar quando alguém ganhou e mudar o estado do jogo)
     - [x] ICriaCha (Leo)
     - [x] IAtaque
     - [x] IMovimento (Leo)
- [x] **PecasMoveis**
     - [x] Configuração das teclas de movimento (2 jogadores)
     - [x] Gráficos das Peças Móveis (+ animações)
     - [x] Inicialização em posições aleatórias
     - [x] IAtaque
     - [x] IMovimento (Leo)
- [x] **PecaInfectado**
- [x] **PecaMedico**
     - [x] ITransferir (João)
     - [x] Contagem visual de itens para cada peça
- [x] **PecaCha**
     - [x] Gráficos do Chá
     - [x] IGuardaCha (João) (falta transformar o atributo "cha" do baú em false)
     - [x] Mudar a posição do chá de acordo com seu carregador
     - [x] ICriaCha (Leo)
- [x] **PecaBau**
     - [x] Inicialização em posições aleatórias
     - [x] Gráficos do Baú
     - [x] IGuardaCha (João)
     - [x] ITransferir (João)

**Comment by LReiz** [comment]
# SÓ PROGRAME NA BRANCH SEC!

## Na branch sec:
**1. git add .** (adiciona suas mudanças no repositório local)
**2. git commit -m "o que foi feito"** (commita pro repositório local)
**3. git checkout master** (vai pra master)


## Na branch master:
**4. git pull** (puxa todo o código do repositório na nuvem)
**5. resolva os conflitos! (se houver)**

**6. git merge sec** (junta a branch sec com a branch master)
**7. resolva os conflitos! (se houver)**

**8. git push** (manda tudo pra nuvem)
**9. git checkout sec** (volta para a branch sec) --> faça logo depois de dar push para não esquecer!

**Comment by jvbm07** [comment]
inicializar o vetorBaus no tabuleiro
